# Form implementation generated from reading ui file 'monitor_window.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt6 import QtCore, QtGui, QtWidgets

class Ui_MonitorWindow(object):
    def setupUi(self, MonitorWindow):
        MonitorWindow.setObjectName("MonitorWindow") # 設置窗口名稱
        MonitorWindow.resize(800, 600) # 設置窗口大小
        self.centralwidget = QtWidgets.QWidget(parent=MonitorWindow) # 創建中央窗口小部件
        self.centralwidget.setObjectName("centralwidget") # 設置中央窗口小部件名稱
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget) # 創建垂直佈局
        self.verticalLayout.setObjectName("verticalLayout") # 設置垂直佈局名稱
        self.lineEdit = QtWidgets.QLineEdit(parent=self.centralwidget) # 創建輸入框
        self.lineEdit.setObjectName("lineEdit") # 設置輸入框名稱
        self.verticalLayout.addWidget(self.lineEdit) # 添加輸入框到垂直佈局
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget) # 創建按鈕
        self.pushButton.setObjectName("pushButton") # 設置按鈕名稱
        self.verticalLayout.addWidget(self.pushButton) # 添加按鈕到垂直佈局
        self.label_open = QtWidgets.QLabel(parent=self.centralwidget) # 創建開盤價標籤
        self.label_open.setObjectName("label_open") # 設置開盤價標籤名稱
        self.verticalLayout.addWidget(self.label_open) # 添加開盤價標籤到垂直佈局
        self.label_high = QtWidgets.QLabel(parent=self.centralwidget) # 創建最高價標籤
        self.label_high.setObjectName("label_high") # 設置最高價標籤名稱
        self.verticalLayout.addWidget(self.label_high) # 添加最高價標籤到垂直佈局
        self.label_low = QtWidgets.QLabel(parent=self.centralwidget) # 創建最低價標籤
        self.label_low.setObjectName("label_low") # 設置最低價標籤名稱
        self.verticalLayout.addWidget(self.label_low) # 添加最低價標籤到垂直佈局
        self.label_volume = QtWidgets.QLabel(parent=self.centralwidget) # 創建成交量標籤
        self.label_volume.setObjectName("label_volume") # 設置成交量標籤名稱
        self.verticalLayout.addWidget(self.label_volume) # 添加成交量標籤到垂直佈局
        self.label_currency = QtWidgets.QLabel(parent=self.centralwidget) # 創建貨幣標籤
        self.label_currency.setObjectName("label_currency") # 設置貨幣標籤名稱
        self.verticalLayout.addWidget(self.label_currency) # 添加貨幣標籤到垂直佈局
        MonitorWindow.setCentralWidget(self.centralwidget) # 設置中央窗口小部件

        self.retranslateUi(MonitorWindow)
        QtCore.QMetaObject.connectSlotsByName(MonitorWindow)

    def retranslateUi(self, MonitorWindow):
        _translate = QtCore.QCoreApplication.translate
        MonitorWindow.setWindowTitle(_translate("MonitorWindow", "股票和虛擬貨幣監控"))
        self.lineEdit.setPlaceholderText(_translate("MonitorWindow", "輸入股票代碼"))
        self.pushButton.setText(_translate("MonitorWindow", "獲取價格"))
        self.label_open.setText(_translate("MonitorWindow", "開盤價: "))
        self.label_high.setText(_translate("MonitorWindow", "最高價: "))
        self.label_low.setText(_translate("MonitorWindow", "最低價: "))
        self.label_volume.setText(_translate("MonitorWindow", "成交量: "))
        self.label_currency.setText(_translate("MonitorWindow", "貨幣: "))